#zf190115.1642
#dépend de https://github.com/zuzu59/docker-ubuntu

FROM docker-ubuntu-zf

MAINTAINER Christian Zufferey <christian@zufferey.com>


RUN apt-get update && apt-get install -yq \
    firefox
