#zf190205.1608
#dépend de https://github.com/zuzu59/docker-ubuntu

FROM docker-ubuntu-zf

MAINTAINER Christian Zufferey <christian@zufferey.com>


RUN apt-get update && apt-get install -yq \
#    unzip \
    firefox

#COPY firefox_config.zip /root
#RUN unzip firefox_config.zip

