#zf181221.1532
#dépend de https://github.com/zuzu59/docker-ubuntu

FROM docker-ubuntu-zf

MAINTAINER Christian Zufferey <christian@zufferey.com>


RUN apt-get update && apt-get install -yq \
    firefox \
    jq \
    bc \
    curl \
    net-tools
